### ISSUE TITLE
MTech Dissertation template

### ISSUE THREAD

**Issue by murtraja** [mgpadalkar/SVNITPhDThesis--noPB-#1]
Do you also happen to have source code for MTech Dissertation Latex template?

**Comment by mgpadalkar** [comment]
Hi Murtaza,

Unfortunately no. These are the only templates I have.
If you wish to, you may yourself modify them into MTech Dissertation LaTeX
template.

Best regards,
Milind

**Comment by murtraja** [comment]
Great, thanks!
